language: node_js
os:
  - windows
node_js:
  - stable
deploy:
  provider: heroku
  app: qworkouts
  api_key:
    secure: yKkJ+yV5Ce8sVyZ1QIwnyv8XAmIDYgJdnE0fla1v0/VxP6cJtRKUn5RS8vC3N1s7ToOYhafYno2+uO7STge2WEaT7BtoB0X/W91Pe6SZdjQcYwu3n5aLyDJnsUc/RhJwp3spfOSDUHEAQZPej/naNQPdbfS59smCkFqgNlKf8YWwA/lWcBV36MwxyclCADjqvC6tzOA+wzx8fXW3KNeOX+h9n9Ucrv7MbPOfrpjH8FYaK/UVQrEEtb5HljWzRopjYmdXUf+7ETPoqYUUqz0uv7HFDHt9CZIFuobUjNAsOGtfSgW41xp45ZsxZWRC3dHfIJf+jlUJlPn3xBG7Uolg82fdBYDiW3pb2tMhRQbZn3El9OGsD+/kBrBPAfNDYFTQchJAXE/+IQzY3ioS4UIxSZK2/vXJFEpSHMkh+GVGd9NB82fHKTEUWdfa3Mbk3dYmh0qihMSCEOG+wIkWzIFvBtsx7UscOr3+8L5PwZdgPSREO737TeI+RFa2hWlEr/FQugBJQdF8dReZFvtCFiDvSy5tRXOxKad4lcPZxjAyHhpLdmGl17zht42D/mtdmKhkoumJ+g4N9BcPJXLa2sk3I6EnnOlBpKLB5JTn0uD4yWET8u4qss0puje6hMTHOu/z72ytA4hjO3GC5AxlCbevLSEml9Ja5Qluz+qvPgQAD8U=
