language: node_js
node_js:
- node
deploy:
  provider: heroku
  app: qworkouts
  api_key:
    secure: TFJ6goRCyatpUWGnUwHx4q6rj1jByZeHDZIpr0RdClMRUzAtQv8AYtEAs6YoZuiUZQnjgqJwQssdtVUcsDElF1+flsopYjGycuWpfUu6cKAmg0rB4ay4saEaB++ppBRuicsVdhhZv22ulZ36Rc1C4zMH7NusCT0jcTUgh0qMxCRi6iEObM7sRCFqGEHv3Bnah7LOeViVzgt+ddTMvXV0ZOgZjPMx/ZGbLZBElcHEPLN+/LgT9bfubFfEp0wmPBGQkLWZi3YYicuujzvLJDUThtKm0JrAVHXG5xKZ7lAM4dIGvCUa2hkKCpDWacHcJC3bL+Jo3gGZlcALWWWJT3KQFZitHqOwFlXAfyltd2rypp/RB5a5Jj1EE+74rum4/Op5jDNqwxWd283Azy9EPutaEw9gY9IC+gh4HJj1QHhpJW/CdF89PMPMtLs07SJb2nyGt+uNEd5F5mrc/3WqZa1H8mcdpvdZEsWba8qP+EXI+sBE6pp5dMeK6rrsni4VhMtw0Uw+wC6SHPsfOvcwBo6x+j83KM5mS9xO+cn/w0g8HhORxP/YQE0WiXKJfQVsTSEe3oOyHB5dZQaiIjrGt8XCgJ+LZRwiO6QCw0+eLMKu5YTCotW3OLOH78C0L9Fbnyb7HhddP82DC6yZpAzk/pa09gePr9UxYSzg2PkY3ff8fuY=
