language: node_js
node_js:
- node
deploy:
  provider: heroku
  app: qworkouts
  api_key:
    secure: qrRE7pWKksOy9KnklgzfogN55mFo3w4r/PxW9hsoiEiTFE/Av2we3gXtAcGAx2GkDsRRdeOv/cKnbE/ruuya3BY1Xu57UirZyQ5lKrmDnJvPx+87NVDqd8+TTJBDIi4hfd1ap7sEMg5otg3W2KC3NxtIPbpFNBi6+nouJibzE5hG0987AEANSMv+Fq1Mu8n7bE9UPNjlTxNEzrg6MZ0TfvKLxM3RNzxCg+Gjx0MLzRRuyRrZIOE5OGyfzfb3PBGpXxCNuR0mzCHZUY/79qQd/13UDtjN0BeM7IPkRS2KyKmUdeoUxdC+5vkFvLP26o4XfNKin3gLH9y5XMVKsLk8PF7dQQtqD1I4gJWChOzkiV6ZlawGJYzCyYlr0Y0e00zaxPCey4qve/CqxBVwXHa48aSIo2rIQ0+SNZRSf+4rqMXGAPNYvjit//yWXVC0ofF7ovXbjXiNV3FCl9rnbCFjaluPZU2PBFmKKXIubgyMxHOnqVT61EryptABoNh9qHvjKWYSOKl1tFMJ3LqM87z4Diiix/ZajpDXKF3SD14w+uWvuhcY5BIblQnmEEzNJnVxVoh2+Q8H+QnNvsN0/tChu/es7a5R6yI2rB3f1diOeWj//GxVsmAQ2XATwXA769dJ2H/2qmMyugRFQWzq2ukqZULQ0C+KujOzkmUC2us9Zbs=
